// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChVRuuGQ3oN8BybO0Ayx5hauEpEREFxY8',
    appId: '1:90210841319:web:0d4bf804d2700fa1f56842',
    messagingSenderId: '90210841319',
    projectId: 'social-media-application-25617',
    authDomain: 'social-media-application-25617.firebaseapp.com',
    storageBucket: 'social-media-application-25617.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFQQrSMLln64hsVvsU6PqUGFF3t4bUG68',
    appId: '1:90210841319:android:cfc73016fd20caf0f56842',
    messagingSenderId: '90210841319',
    projectId: 'social-media-application-25617',
    storageBucket: 'social-media-application-25617.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBASIKVJY_PF5zhY1Wql5llza7ddVlcUAQ',
    appId: '1:90210841319:ios:6a8d7a73e24e6478f56842',
    messagingSenderId: '90210841319',
    projectId: 'social-media-application-25617',
    storageBucket: 'social-media-application-25617.appspot.com',
    iosClientId: '90210841319-dq1msfrj3o43hmd3vpleq4eb1oenbcvr.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialMediaApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBASIKVJY_PF5zhY1Wql5llza7ddVlcUAQ',
    appId: '1:90210841319:ios:6a8d7a73e24e6478f56842',
    messagingSenderId: '90210841319',
    projectId: 'social-media-application-25617',
    storageBucket: 'social-media-application-25617.appspot.com',
    iosClientId: '90210841319-dq1msfrj3o43hmd3vpleq4eb1oenbcvr.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialMediaApplication',
  );
}
